



// C

int Emulate6502( unsigned char *A, unsigned char *X, unsigned char *Y, unsigned char *SP, unsigned int *PC, unsigned char *SR, unsigned char *memory ) {
  unsigned char instruction = memory[PC & 0xFFFF];
  if( instruction == 0x00 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int readWord := memory[(0xFFFE)&0xFFFF] + (memory[((0xFFFE)+1)&0xFFFF]<<8); unsigned char newSP = SP - 3; unsigned int newPC = (readWord)&0xFFFF; *SP = newSP; *PC = newPC; unsigned char carry = SR&1; unsigned char zero = (SR>>1)&1; unsigned char interrupt = 0x1;unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = readWord;memory[(SP - 2)&0xFFFF] = SR | 0x10; memory[(SP - 1)&0xFFFF] = (PC + 2)&0xFF; memory[((SP - 1)+1)&0xFFFF] = ((PC + 2)>>8&0xFF; return true; }
  if( instruction == 0x01 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x05 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x06 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte << 1; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x08 ) { unsigned char newSP = SP - 1; *SP = newSP; *PC = PC + 1; memory[(SP)&0xFFFF] = SR | 0x30; return true; }
  if( instruction == 0x09 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = A | LL; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x0A ) { unsigned int result = A << 1; unsigned char newA = result; *A = newA; unsigned char carry = A >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x0D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; *PC = PC + 3; return true; }
  if( instruction == 0x0E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte << 1; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x10 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (negative-1)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (negative-1));return true; }
  if( instruction == 0x11 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + Y)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x15 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x16 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = readByte << 1; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x18 ) { unsigned char carry = 0x0;unsigned char zero = (SR>>1)&1; unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x19 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x1D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = A | readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x1E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = readByte << 1; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x20 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char newSP = SP - 2; unsigned int newPC = (HHLL)&0xFFFF; *SP = newSP; *PC = newPC; *PC = HHLL;memory[(SP - 1)&0xFFFF] = (PC + 3)&0xFF; memory[((SP - 1)+1)&0xFFFF] = ((PC + 3)>>8&0xFF; return true; }
  if( instruction == 0x21 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x24 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A & readByte; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = readByte >> 6;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x25 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x26 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = (readByte << 1) + carry; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x28 ) { unsigned char readByte = memory[(SP + 1)&0xFFFF]; unsigned int result = readByte; unsigned char newSP = SP + 1; *SP = newSP; unsigned char carry = result;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = result >> 2;unsigned char decimal = result >> 3;unsigned char overflow = 0;unsigned char negative = result >> 6;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x29 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = A & LL; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x2A ) { unsigned int result = (A << 1) + carry; unsigned char newA = result; *A = newA; unsigned char carry = A >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x2C ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A & readByte; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = readByte >> 6;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x2D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x2E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = (readByte << 1) + carry; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x30 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (-negative)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (-negative));return true; }
  if( instruction == 0x31 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + Y)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x35 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x36 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = (readByte << 1) + carry; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x38 ) { unsigned char carry = 0x1;unsigned char zero = (SR>>1)&1; unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x39 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x3D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = A & readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x3E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = (readByte << 1) + carry; unsigned char carry = readByte >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x40 ) { unsigned char readByte = memory[(SP + 1)&0xFFFF]; unsigned int readWord := memory[(SP + 3)&0xFFFF] + (memory[((SP + 3)+1)&0xFFFF]<<8); unsigned char newSP = SP + 3; unsigned int newPC = (readWord)&0xFFFF; *SP = newSP; *PC = newPC; unsigned char carry = result;unsigned char zero = result >> 1;unsigned char interrupt = result >> 2;unsigned char decimal = result >> 3;unsigned char overflow = 0;unsigned char negative = result >> 6;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = readWord;return true; }
  if( instruction == 0x41 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x45 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x46 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte >> 1; unsigned char newA = result; *A = newA; unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x48 ) { unsigned char newSP = SP - 1; *SP = newSP; *PC = PC + 1; memory[(SP)&0xFFFF] = A; return true; }
  if( instruction == 0x49 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = A ^ LL; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x4A ) { unsigned int result = A >> 1; unsigned char newA = result; *A = newA; unsigned char carry = A;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x4C ) { unsigned int newPC = (HHLL)&0xFFFF; *PC = newPC; *PC = HHLL;return true; }
  if( instruction == 0x4D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x4E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte >> 1; unsigned char newA = result; *A = newA; unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x50 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (overflow-1)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (overflow-1));return true; }
  if( instruction == 0x51 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + Y)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x55 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x56 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = readByte >> 1; unsigned char newA = result; *A = newA; unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x58 ) { unsigned char carry = SR&1; unsigned char zero = (SR>>1)&1; unsigned char interrupt = 0x0;unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x59 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x5D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = A ^ readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x5E ) { unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = readByte >> 1; unsigned char newA = result; *A = newA; unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x60 ) { unsigned int readWord := memory[(SP + 1)&0xFFFF] + (memory[((SP + 1)+1)&0xFFFF]<<8); unsigned char newSP = SP + 2; unsigned int newPC = (readWord)&0xFFFF; *SP = newSP; *PC = newPC; *PC = readWord;return true; }
  if( instruction == 0x61 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x65 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x66 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = (readByte >> 1) + (carry << 7); unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x68 ) { unsigned char readByte = memory[(SP + 1)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x69 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = A + LL + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x6A ) { unsigned int result = (A >> 1) + (carry << 7); unsigned char newA = result; *A = newA; unsigned char carry = A;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x6C ) { unsigned int readWord := memory[(HHLL)&0xFFFF] + (memory[((HHLL)+1)&0xFFFF]<<8); unsigned int newPC = (readWord)&0xFFFF; *PC = newPC; *PC = readWord;return true; }
  if( instruction == 0x6D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x6E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = (readByte >> 1) + (carry << 7); unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x70 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (-overflow)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (-overflow));return true; }
  if( instruction == 0x71 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + Y)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x75 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0x76 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = (readByte >> 1) + (carry << 7); unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x78 ) { unsigned char carry = SR&1; unsigned char zero = (SR>>1)&1; unsigned char interrupt = 0x1;unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x79 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x7D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = A + readByte + carry; unsigned char newA = result; *A = newA; unsigned char carry = (A - result) >> 7;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ((A ^ result) & (readByte ^ result)) >> 7;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0x7E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = (readByte >> 1) + (carry << 7); unsigned char carry = readByte;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0x81 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); *PC = PC + 2; memory[(zeroPageWord)&0xFFFF] = A; return true; }
  if( instruction == 0x84 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; *PC = PC + 2; memory[(LL)&0xFFFF] = Y; return true; }
  if( instruction == 0x85 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; *PC = PC + 2; memory[(LL)&0xFFFF] = A; return true; }
  if( instruction == 0x86 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; *PC = PC + 2; memory[(LL)&0xFFFF] = X; return true; }
  if( instruction == 0x88 ) { unsigned int result = Y - 1; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x8A ) { unsigned int result = X; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x8C ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); *PC = PC + 3; memory[(HHLL)&0xFFFF] = Y; return true; }
  if( instruction == 0x8D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); *PC = PC + 3; memory[(HHLL)&0xFFFF] = A; return true; }
  if( instruction == 0x8E ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); *PC = PC + 3; memory[(HHLL)&0xFFFF] = X; return true; }
  if( instruction == 0x90 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (carry-1)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (carry-1));return true; }
  if( instruction == 0x91 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); *PC = PC + 2; memory[(zeroPageWord + Y)&0xFFFF] = A; return true; }
  if( instruction == 0x94 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; *PC = PC + 2; memory[((LL + X) & 0xFF)&0xFFFF] = Y; return true; }
  if( instruction == 0x95 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; *PC = PC + 2; memory[((LL + X) & 0xFF)&0xFFFF] = A; return true; }
  if( instruction == 0x96 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); *PC = PC + 2; memory[(zeroPageWord + Y)&0xFFFF] = X; return true; }
  if( instruction == 0x98 ) { unsigned int result = Y; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0x99 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); *PC = PC + 3; memory[(HHLL + Y)&0xFFFF] = A; return true; }
  if( instruction == 0x9A ) { unsigned int result = X; unsigned char newSP = result; *SP = newSP; *PC = PC + 1; return true; }
  if( instruction == 0x9D ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); *PC = PC + 3; memory[(HHLL + X)&0xFFFF] = A; return true; }
  if( instruction == 0xA0 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = LL; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xA1 ) { unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xA2 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = LL; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xA4 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xA5 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xA6 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xA8 ) { unsigned int result = A; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xA9 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = LL; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xAA ) { unsigned int result = A; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xAC ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xAD ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xAE ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xB0 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (-carry)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (-carry));return true; }
  if( instruction == 0xB1 ) { unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + Y)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xB4 ) { unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = readByte; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xB5 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xB6 ) { unsigned char readByte = memory[((LL + Y) & 0xFF)&0xFFFF]; unsigned int result = readByte; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xB8 ) { unsigned char carry = SR&1; unsigned char zero = (SR>>1)&1; unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = 0x0;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xB9 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xBA ) { unsigned int result = SP; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xBC ) { unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xBD ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = readByte; unsigned char newA = result; *A = newA; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xBE ) { unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = readByte; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xC0 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = Y - LL; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xC1 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xC4 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = Y - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xC5 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xC6 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte - 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xC8 ) { unsigned int result = Y + 1; unsigned char newY = result; *Y = newY; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xC9 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = A - LL; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xCA ) { unsigned int result = X - 1; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xCC ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = Y - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xCD ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xCE ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte - 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xD0 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (zero-1)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (zero-1));return true; }
  if( instruction == 0xD1 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL)&0xFF] + (memory[((LL)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + YY)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xD5 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xD6 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = readByte - 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xD8 ) { unsigned char carry = SR&1; unsigned char zero = (SR>>1)&1; unsigned char interrupt = (SR>>2)&1; unsigned char decimal = 0x0;unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xD9 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xDD ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = A - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xDE ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = readByte - 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xE0 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = X - LL; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xE1 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xE4 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = X - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xE5 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xE6 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[(LL)&0xFFFF]; unsigned int result = readByte + 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xE8 ) { unsigned int result = X + 1; unsigned char newX = result; *X = newX; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xE9 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int result = A - LL - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xEA ) { *PC = PC + 1; return true; }
  if( instruction == 0xEC ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = X - readByte; unsigned char carry = 1 - (result >> 7);unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xED ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xEE ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL)&0xFFFF]; unsigned int result = readByte + 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xF0 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int newPC = (PC + 2 + (LL & (-zero)))&0xFFFF; *PC = newPC; *PC = PC + 2 + (LL & (-zero));return true; }
  if( instruction == 0xF1 ) { unsigned int zeroPageWord = memory[(LL + X)&0xFF] + (memory[((LL + X)+1)&0xFF]<<8); unsigned char readByte = memory[(zeroPageWord + Y)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xF5 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; return true; }
  if( instruction == 0xF6 ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned char readByte = memory[((LL + X) & 0xFF)&0xFFFF]; unsigned int result = readByte + 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 2; memory[(readByteAddress)&0xFFFF] = result; return true; }
  if( instruction == 0xF8 ) { unsigned char carry = SR&1; unsigned char zero = (SR>>1)&1; unsigned char interrupt = (SR>>2)&1; unsigned char decimal = 0x1;unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xF9 ) { unsigned char readByte = memory[(HHLL + Y)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 1; return true; }
  if( instruction == 0xFD ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = A - readByte - (carry^1); unsigned char newA = result; *A = newA; unsigned char carry = ???;unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = ???;*SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; return true; }
  if( instruction == 0xFE ) { unsigned char LL = memory[(PC+1)&0xFFFF]; unsigned int HH = memory[(PC+2)&0xFFFF]; unsigned int HHLL = LL + (HH<<8); unsigned char readByte = memory[(HHLL + X)&0xFFFF]; unsigned int result = readByte + 1; unsigned char carry = SR&1; unsigned char zero = (result | -result) >> 7;unsigned char interrupt = (SR>>2)&1; unsigned char decimal = (SR>>3)&1; unsigned char overflow = (SR>>6)&1; unsigned char negative = (SR>>7)&1; *SR = carry + (zero<<1) + (interrupt<<2) + (decimal<<3) + (overflow<<6) + (negative<<7); *PC = PC + 3; memory[(readByteAddress)&0xFFFF] = result; return true; }
  return false;
}


